version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels: ["deps"]
    rebase-strategy: "auto"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels: ["deps"]
    rebase-strategy: "auto"