[package]
name = "mvp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19"
tower-http = { version = "0.6", features = ["cors"] }

# Pokud teď nevoláš vzdálené API, klidně smaž i reqwest.
# reqwest = { version = "0.12", features = ["json"] }

# Shuttle (deploy + Axum re-export)
shuttle-runtime = "0.56.0"
shuttle-axum = "0.56.0"