[package]
name = "dow-sentiment-analyzer"
version = "0.1.0"
edition = "2021"
description = "A sentiment analysis and decision engine for Dow Jones futures, built with Rust, Axum, and Tokio."
license = "MIT"
authors = ["Lumir Lichy <lumlich@lumlich.com>"]
repository = "https://github.com/lumlich/dow-sentiment-analyzer"
readme = "README.md"

[dependencies]
# Async runtime
tokio = { version = "1.47", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
once_cell = "1.19"

# HTTP extensions (e.g. CORS middleware)
tower-http = { version = "0.6", features = ["cors"] }

# Shuttle (deployment runtime + Axum re-export)
shuttle-runtime = "0.56.0"
shuttle-axum = "0.56.0"

# Optional: Uncomment if external API calls are needed
# reqwest = { version = "0.12", features = ["json"] }

[features]
default = []
debug = []