# .cargo/config.toml
[alias]
# Run all unit tests in this crate
t = "test"

# Run only unit tests in this crate (explicit)
tu = "test -p dow-sentiment-analyzer"

# Run the synthetic (ignored) suite (prints pass/fail table)
ts = "test --test relevance_synthetic -- --ignored --nocapture"

# Clippy & fmt helpers (useful in CI)
cf = "fmt --all -- --check"
cl = "clippy --workspace --all-features -- -D warnings"