# Relevance Gate Configuration (precision-first)
# - Anchors are regexes with optional proximity constraints (near = { pattern, window }).
# - Categories carry weights. Scoring logic in code will combine categories conservatively.
# - Blockers are hard filters; if matched, the sample is rejected (unless code later adds overrides).

[relevance]
threshold = 0.30           # normalized pass threshold (final logic also enforces combo rules)
near_default_window = 6    # default token window for proximity checks

[weights]
hard = 3
semi = 2
macro = 2
soft = 1
verb = 1

# =========================
# Anchors (each is an item)
# =========================
[[anchors]]
id = "djia_core_names"
category = "hard"
pattern = "(?i)\\b(djia|dow jones|the dow|dow 30|30-stock index|blue[- ]chip index)\\b"

[[anchors]]
id = "djia_industrial_average"
category = "hard"
pattern = "(?i)\\b(dow jones industrial average|industrial average|dow industrials|the industrials)\\b"

[[anchors]]
id = "djia_symbols"
category = "hard"
pattern = "(?i)(\\$DJI|\\^DJI|#DJIA|#DowJones)\\b"

[[anchors]]
id = "dow_bare_near_market"
category = "hard"
pattern = "(?i)\\bdow\\b"
near = { pattern = "(?i)\\b(jones|djia|index|equities|stocks?|futures?)\\b", window = 6 }

# NEW: plain "Dow" as hard anchor
[[anchors]]
id = "dow_bare"
category = "hard"
pattern = "(?i)\\bdow\\b"

[[anchors]]
id = "djia_futures_ym"
category = "hard"
pattern = "(?i)\\b(ym|mym)\\b"
near = { pattern = "(?i)\\b(futures?|e-?mini|micro\\s*e-?mini|cbot)\\b", window = 3 }

[[anchors]]
id = "market_context_core"
category = "semi"
pattern = "(?i)\\b(wall street|equities|stocks?|stock market|markets?|market breadth)\\b"

[[anchors]]
id = "market_microstructure"
category = "semi"
pattern = "(?i)\\b(futures?|pre-?market|after-?hours|opening bell|closing bell|limit up|limit down|volatility|volatile)\\b"

[[anchors]]
id = "risk_phrases"
category = "semi"
pattern = "(?i)\\b(risk-?on|risk-?off|bear market|bull market|sell-?off|rally)\\b"

# ----- Macro / Policy with market impact -----
[[anchors]]
id = "fed_core"
category = "macro"
pattern = "(?i)\\b(fed|federal reserve|fomc)\\b"

[[anchors]]
id = "powell_any"
category = "macro"
pattern = "(?i)\\b(jerome\\s+powell|powell)\\b"

[[anchors]]
id = "powell_near_fed_rates"
category = "macro"
pattern = "(?i)\\bpowell\\b"
near = { pattern = "(?i)\\b(fed|federal reserve|rates?|rate (hike|cut|decision|path)|fomc)\\b", window = 6 }

[[anchors]]
id = "powell_fed_near_dow_context"
category = "macro"
pattern = "(?i)\\b(powell|fed|federal reserve|fomc)\\b"
near = { pattern = "(?i)\\b(dow|djia|the dow|industrial average|equities|stocks?|futures?)\\b", window = 20 }

[[anchors]]
id = "yellen_near_treasury"
category = "macro"
pattern = "(?i)\\byellen\\b"
near = { pattern = "(?i)\\b(treasury|yields?|auction|notes?)\\b", window = 6 }

[[anchors]]
id = "macro_indicators"
category = "macro"
pattern = "(?i)\\b(cpi|pce|ppi|nfp|jobs? report|unemployment|payrolls?|gdp|retail sales|ism|pmi)\\b"

[[anchors]]
id = "rates_yields_policy"
category = "macro"
pattern = "(?i)\\b(treasury yields?|10-?year|ust10y|yield curve|rate (hike|cut)s?|policy|qt|qe|tariffs?|sanctions?)\\b"

# ----- Cross-index (soft) -----
[[anchors]]
id = "cross_index_spx_ndx"
category = "soft"
pattern = "(?i)\\b(s&p\\s*500|s\\&p\\s*500|spx|\\$spx|es|\\$es|nasdaq|ndx|\\$nq)\\b"

# ----- Market movement verbs (soft) -----
[[anchors]]
id = "price_action_verbs_up"
category = "verb"
pattern = "(?i)\\b(surge|soar|jump|pop|rally|spike)\\b"

[[anchors]]
id = "price_action_verbs_down"
category = "verb"
pattern = "(?i)\\b(slump|plunge|tank|sell\\s*off|whipsaw)\\b"

# ----- Single-stock caution (informational anchor; handled conservatively in code) -----
[[anchors]]
id = "dow_inc_ticker"
category = "soft"
pattern = "(?i)\\$DOW\\b"
tag = "single_stock_only"

# ================
# Blockers (hard)
# ================
[[blockers]]
id = "dow_homonyms"
pattern = "(?i)\\b(downtown|downton|downey|dowel|dowry|window|shadow)\\b"
reason = "Non-financial 'dow' substrings"
action = "block"

[[blockers]]
id = "dji_drones"
pattern = "(?i)\\bdji\\b"
near = { pattern = "(?i)\\b(drone|mavic|gimbal|osmo|fpv)\\b", window = 4 }
reason = "DJI (drones), not the index"
action = "block"

[[blockers]]
id = "downton_abbey"
pattern = "(?i)\\bdownton\\s+abbey\\b"
reason = "TV show"
action = "block"

[[blockers]]
id = "robert_downey"
pattern = "(?i)\\brobert\\s+downey\\b"
reason = "Actor"
action = "block"

[[blockers]]
id = "down_syndrome_phrase"
pattern = "(?i)\\bdown\\s+syndrome\\b"
reason = "Medical context"
action = "block"

[[blockers]]
id = "dow_inc_company"
pattern = "(?i)\\bdow inc\\.?\\b|\\bdow chemical\\b"
reason = "Company context (Dow Inc.), not DJIA"
action = "block"

[[blockers]]
id = "dow_inc_without_market_context"
pattern = "(?i)\\$DOW\\b"
unless_near = { pattern = "(?i)\\b(djia|dow jones|the dow|index|stock market|markets?|wall street|futures?)\\b", window = 6 }
reason = "Single-stock ticker likely unrelated to DJIA"
action = "block"

# ==========================
# Required combo suggestions
# ==========================
[[combos.pass_any]]
need = ["hard", "verb"]

[[combos.pass_any]]
need = ["hard", "semi"]

[[combos.pass_any]]
need = ["macro", "hard"]

[[combos.pass_any]]
need = ["macro", "macro", "verb_or_semi"]

[[combos.pass_any]]
need = ["semi", "semi", "soft", "verb"]

[aliases]
verb_or_semi = ["verb","semi"]