// src/spa.rs
// All code and comments intentionally in English.
use axum::{
    body::Body,
    http::{header, HeaderValue, StatusCode},
    response::{Html, IntoResponse, Response},
    routing::{get, get_service},
    Router,
};
use std::{io, time::Duration};
use tower::ServiceBuilder;
use tower_http::{
    compression::CompressionLayer,
    services::{ServeDir, ServeFile},
    set_header::SetResponseHeaderLayer,
    trace::TraceLayer,
};

/// Embed the built UI HTML (generated by `ui.off`).
/// Make sure you have run `npm run build` in `ui.off`.
pub const INDEX_HTML: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/ui.off/dist/index.html"));

fn index_response() -> impl IntoResponse {
    // No caching for the index to always pick latest assets by hashed filenames.
    let headers = [
        (header::CONTENT_TYPE, HeaderValue::from_static("text/html; charset=utf-8")),
        (header::CACHE_CONTROL, HeaderValue::from_static("no-store")),
    ];
    (headers, Html(INDEX_HTML))
}

async fn index_handler() -> impl IntoResponse {
    index_response()
}

async fn io_error_handler(err: io::Error) -> (StatusCode, String) {
    (StatusCode::INTERNAL_SERVER_ERROR, format!("Static file error: {err}"))
}

/// Attach SPA routes (/ , /assets/*, /favicon.ico, and SPA fallback) to an existing app router.
/// This preserves all your existing mounts like /api/*, /_version, /_health, /metrics.
pub fn attach_spa_routes<S>(app: Router<S>) -> Router<S>
where
    S: Clone + Send + Sync + 'static,
{
    // Static assets service with strong caching (immutable hashed files).
    let assets_service = get_service(
        ServeDir::new("assets")
            .precompressed_gzip()
            .precompressed_br()
            .precompressed_deflate(),
    )
    .handle_error(io_error_handler)
    .layer(SetResponseHeaderLayer::if_not_present(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=31536000, immutable"),
    ));

    // Favicon service (packaged via Shuttle [build] assets).
    let favicon_service = get_service(ServeFile::new("favicon.ico")).handle_error(io_error_handler);

    // Compose layers for logging and compression on dynamic responses.
    let common_layers = ServiceBuilder::new()
        .layer(TraceLayer::new_for_http())
        .layer(CompressionLayer::new());

    app.route("/", get(index_handler))
        .route_service("/favicon.ico", favicon_service)
        .route_service("/assets/*path", assets_service)
        // SPA fallback: anything not matched before goes to index.html
        .fallback_service(get(index_handler))
        .layer(common_layers)
}
