name: Security audit
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"  # denne v 03:00 UTC

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rust-lang/audit@v1
